#
# TM Simulator
#

CC = gcc

CFLAGS = 

tm: tm.c
	$(CC) $(CFLAGS) tm.c -o tm

clean:
	-rm -f tm

test1:
	./tm ../C-programs/1.tm

test2:
	./tm ../C-programs/2.tm

test3:
	./tm ../C-programs/3.tm

test4:
	./tm ../C-programs/4.tm

test5:
	./tm ../C-programs/5.tm

test6:
	./tm ../C-programs/6.tm

test7:
	./tm ../C-programs/7.tm

test8:
	./tm ../C-programs/8.tm
	
test9:
	./tm ../C-programs/9.tm

test0:
	./tm ../C-programs/0.tm